# ==========================================================
#  Training Configurations
# ==========================================================
config_list = [  # -------------- RNNs --------------
               {'model': {'type': 'RNN', 'em_dim': 64, 'hidden_size': 128, 'n_layers': 1, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                'lr': 1e-3,
                'n_epochs': 10,
                'batch_size': 32,
                'block_size': 128,
                'print_every': 1,
                'eval_every': 2,
                'n_generate': 360,
                'tok_type': 'char'},
               
               {'model': {'type': 'RNN', 'em_dim': 64, 'hidden_size': 128, 'n_layers': 3, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                'lr': 1e-3,
                'n_epochs': 150,
                'batch_size': 32,
                'block_size': 128,
                'print_every': 1,
                'eval_every': 2,
                'n_generate': 360,
                'tok_type': 'char'},
               
               {'model': {'type': 'RNN', 'em_dim': 128, 'hidden_size': 216, 'n_layers': 1, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                'lr': 1e-3,
                'n_epochs': 150,
                'batch_size': 32,
                'block_size': 128,
                'print_every': 1,
                'eval_every': 2,
                'n_generate': 360,
                'tok_type': 'char'},
               
               {'model': {'type': 'RNN', 'em_dim': 128, 'hidden_size': 216, 'n_layers': 3, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                'lr': 1e-3,
                'n_epochs': 150,
                'batch_size': 32,
                'block_size': 128,
                'print_every': 1,
                'eval_every': 2,
                'n_generate': 360,
                'tok_type': 'char'},
               
                {'model': {'type': 'RNN', 'em_dim': 64, 'hidden_size': 128, 'n_layers': 1, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                {'model': {'type': 'RNN', 'em_dim': 64, 'hidden_size': 128, 'n_layers': 3, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                {'model': {'type': 'RNN', 'em_dim': 128, 'hidden_size': 216, 'n_layers': 1, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                {'model': {'type': 'RNN', 'em_dim': 128, 'hidden_size': 216, 'n_layers': 3, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                    
                # -------------- LSTMs --------------
                {'model': {'type': 'LSTM', 'em_dim': 64, 'hidden_size': 128, 'n_layers': 1, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 360,
                 'tok_type': 'char'},
                
                {'model': {'type': 'LSTM', 'em_dim': 64, 'hidden_size': 128, 'n_layers': 3, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 360,
                 'tok_type': 'char'},
                
                {'model': {'type': 'LSTM', 'em_dim': 128, 'hidden_size': 216, 'n_layers': 1, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 360,
                 'tok_type': 'char'},
                
                {'model': {'type': 'LSTM', 'em_dim': 128, 'hidden_size': 216, 'n_layers': 3, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 360,
                 'tok_type': 'char'},
                
                {'model': {'type': 'LSTM', 'em_dim': 64, 'hidden_size': 128, 'n_layers': 1, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                {'model': {'type': 'LSTM', 'em_dim': 64, 'hidden_size': 128, 'n_layers': 3, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                {'model': {'type': 'LSTM', 'em_dim': 128, 'hidden_size': 216, 'n_layers': 1, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                {'model': {'type': 'LSTM', 'em_dim': 128, 'hidden_size': 216, 'n_layers': 3, 'weight_decay': 1e-4, 'dropout': 0.2}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 128,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                # -------------- GPTs --------------
                {'model': {'type': 'GPT', 'd_model': 128, 'n_heads':2, 'n_layers': 2, 'weight_decay': 1e-4, 'dropout': 0.2, 'bias': False}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 512,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 360,
                 'tok_type': 'char'},
                
                {'model': {'type': 'GPT', 'd_model': 216, 'n_heads':4,'n_layers': 4, 'weight_decay': 1e-4, 'dropout': 0.2, 'bias': False}, 
                 'lr': 1e-3,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 512,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 360,
                 'tok_type': 'char'},
                
                {'model': {'type': 'GPT', 'd_model': 128, 'n_heads':2, 'n_layers': 2, 'weight_decay': 1e-4, 'dropout': 0.2, 'bias': False}, 
                 'lr': 1e-4,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 256,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                {'model': {'type': 'GPT', 'd_model': 216, 'n_heads':4, 'n_layers': 4, 'weight_decay': 1e-4, 'dropout': 0.2, 'bias': False}, 
                 'lr': 1e-4,
                 'n_epochs': 150,
                 'batch_size': 32,
                 'block_size': 256,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'bpe'},
                
                # -------------- GPT2 --------------               
                {'model': {'type': 'GPT2', 'use_lora': True, 'train_layernorm': True, 'last_k_layers': 2, 'weight_decay': 1e-2},
                 'lr': 1e-5,
                 'n_epochs': 50,
                 'batch_size': 4,
                 'block_size': 256,
                 'print_every': 1,
                 'eval_every': 2,
                 'n_generate': 90,
                 'tok_type': 'gpt2'},
                
                 ]