EXPERIMENTS_VGG = [
    dict(id="baseline_vgg",
         MODEL='VGG', LR=0.001,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=1,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.0, DROPOUT_VAR=False, USE_BN=False, REMOVE_LAST_MAXPOOL=False,
         WEIGHT_DECAY=0.0, AUGMENT=False, LABEL_SMOOTH=0.0,
         SCHEDULER="CyclicLR", EPOCHS=30, OPTIMIZER="Adam"),

    dict(id="vgg_plus",
         MODEL='VGG', LR=0.001,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.0, DROPOUT_VAR=False, USE_BN=False, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=False, LABEL_SMOOTH=0.0,
         SCHEDULER="CyclicLR", EPOCHS=30, OPTIMIZER="Adam"),

    dict(id="vgg_plus_dropout",
         MODEL='VGG', LR=0.001,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.2, DROPOUT_VAR=False, USE_BN=False, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=False, LABEL_SMOOTH=0.0,
         SCHEDULER="CyclicLR", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_weight_decay",
         MODEL='VGG', LR=0.001,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.0, DROPOUT_VAR=False, USE_BN=False, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.001, AUGMENT=False, LABEL_SMOOTH=0.0,
         SCHEDULER="CyclicLR", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_data_augmentation",
         MODEL='VGG', LR=0.001,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.0, DROPOUT_VAR=False, USE_BN=False, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=True, LABEL_SMOOTH=0.0,
         SCHEDULER="CyclicLR", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_combo",
         MODEL='VGG', LR=0.005,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.2, DROPOUT_VAR=True, USE_BN=True, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=True, LABEL_SMOOTH=0.0,
         SCHEDULER="CyclicLR", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_combo_label_smooth",
         MODEL='VGG', LR=0.005,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.2, DROPOUT_VAR=True, USE_BN=True, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=True, LABEL_SMOOTH=0.2,
         SCHEDULER="CyclicLR", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_combo_step_LR",
         MODEL='VGG', LR=0.001,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.2, DROPOUT_VAR=True, USE_BN=True, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=True, LABEL_SMOOTH=0.0,
         SCHEDULER="StepLR", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_combo_cosine",
         MODEL='VGG', LR=0.001,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=False,
         DROPOUT=0.2, DROPOUT_VAR=True, USE_BN=True, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=True, LABEL_SMOOTH=0.0,
         SCHEDULER="CosineAnnealWarmRest", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_combo_conv_down_samp",
         MODEL='VGG', LR=0.005,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=False, CONV_DOWN_SAMP=True,
         DROPOUT=0.2, DROPOUT_VAR=True, USE_BN=True, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=True, LABEL_SMOOTH=0.0,
         SCHEDULER="CyclicLR", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_combo_gap_head",
         MODEL='VGG', LR=0.005,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=True, CONV_DOWN_SAMP=False,
         DROPOUT=0.2, DROPOUT_VAR=True, USE_BN=True, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=True, LABEL_SMOOTH=0.0,
         SCHEDULER="CyclicLR", EPOCHS=40, OPTIMIZER="Adam"),
    
    dict(id="vgg_plus_final_combo",
         MODEL='VGG', LR=0.005,
         PATCH_F=2, PATCH_NF=64, VGG_BLOCKS=3,
         FC_DIM=128, GLOBAL_AVG_POOL=True, CONV_DOWN_SAMP=False,
         DROPOUT=0.2, DROPOUT_VAR=True, USE_BN=True, REMOVE_LAST_MAXPOOL=True,
         WEIGHT_DECAY=0.0, AUGMENT=True, LABEL_SMOOTH=0.2,
         SCHEDULER="CyclicLR", EPOCHS=40, OPTIMIZER="Adam"),

]

EXPERIMENTS_RES = [
    dict(id="res_label_smooth",
        MODEL='Res', SHORTCUT='Identity',
        N_RES=3, SE_ACTIVATE=False, CBAM_ACTIVATE=False,
        WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
        SCHEDULER="Decay", EPOCHS=60,
        LR=0.1, OPTIMIZER="SGD", DATASET='CIFAR10'),
    
    dict(id="res_label_smooth_proj",
        MODEL='Res', SHORTCUT='Projection',
        N_RES=3, SE_ACTIVATE=False, CBAM_ACTIVATE=False,
        WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
        SCHEDULER="Decay", EPOCHS=60,
        LR=0.1, OPTIMIZER="SGD", DATASET='CIFAR10'),
    
    dict(id="res_adam_label_smooth",
         MODEL='Res', SHORTCUT='Identity',
         N_RES=3, SE_ACTIVATE=False, CBAM_ACTIVATE=False,
         WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
         SCHEDULER="Decay", EPOCHS=60,
         LR=0.01, OPTIMIZER="Adam", DATASET='CIFAR10'),
    
    dict(id="res_adam_label_smooth_cosine",
         MODEL='Res', SHORTCUT='Identity',
         N_RES=3, SE_ACTIVATE=False, CBAM_ACTIVATE=False,
         WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
         SCHEDULER="CosineAnnealWarmRest", EPOCHS=60,
         LR=0.01, OPTIMIZER="Adam", DATASET='CIFAR10'),
    
    dict(id="res_label_smooth_100",
        MODEL='Res', SHORTCUT='Identity',
        N_RES=3, SE_ACTIVATE=False, CBAM_ACTIVATE=False,
        WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
        SCHEDULER="Decay", EPOCHS=60,
        LR=0.1, OPTIMIZER="SGD", DATASET='CIFAR100'),
    
]

EXPERIMENTS_SE_RES = [
    dict(id="se_res_label_smooth_baseline",
        MODEL='Res', SHORTCUT='Identity',
        N_RES=3, SE_ACTIVATE=True, CBAM_ACTIVATE=False,
        WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
        SCHEDULER="Decay", EPOCHS=60,
        LR=0.1, OPTIMIZER="SGD", DATASET='CIFAR10'),
    
    dict(id="se_res_label_smooth_baseline_100",
        MODEL='Res', SHORTCUT='Identity',
        N_RES=3, SE_ACTIVATE=True, CBAM_ACTIVATE=False,
        WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
        SCHEDULER="Decay", EPOCHS=60,
        LR=0.1, OPTIMIZER="SGD", DATASET='CIFAR100'),
]

EXPERIMENTS_CBAM_RES =  [
    dict(id="cbam_res_label_smooth_baseline",
        MODEL='Res', SHORTCUT='Identity',
        N_RES=3, SE_ACTIVATE=False, CBAM_ACTIVATE=True,
        WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
        SCHEDULER="Decay", EPOCHS=60,
        LR=0.1, OPTIMIZER="SGD", DATASET='CIFAR10'),
    
    dict(id="cbam_res_label_smooth_baseline_100",
        MODEL='Res', SHORTCUT='Identity',
        N_RES=3, SE_ACTIVATE=False, CBAM_ACTIVATE=True,
        WEIGHT_DECAY=1e-4, AUGMENT=True, LABEL_SMOOTH=0.1,
        SCHEDULER="Decay", EPOCHS=60,
        LR=0.1, OPTIMIZER="SGD", DATASET='CIFAR100'),
]